# For production
# Build with BuildKit:
# COMPOSE_DOCKER_CLI_BUILD=1 DOCKER_BUILDKIT=1 docker-compose build
services:
  app:
    build:
      context: .
      target: production
    ports:
      - "8000:8000"
    restart: always
    env_file:
      - .env
