# For development
# Build with BuildKit:
# COMPOSE_DOCKER_CLI_BUILD=1 DOCKER_BUILDKIT=1 docker-compose build
services:
  app:
    build:
      context: .
      target: dev
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - DEBUG=*
